baseURL = 'https://chajs226.github.io/hugo_blog/'
languageCode = 'ko-kr'
title = "Junseong's Story"
theme = 'maverick'

[permalinks]
  pages = "/:slug"

[params]
  logo = '/assets/favicon.ico'
  description = "Junseong's Story"
  author = '차준성'
  items = 10

  [params.comments]
    enabled = false


[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/hugo_blog/posts/"
    weight = 1
  [[menu.main]]
    identifier = "playgound"
    name = "Playground"
    url = "/hugo_blog/playground/"
    weight = 2
  [[menu.main]]
    identifier = "notes"
    name = "Notes"
    url = "/hugo_blog/notes/"
    weight = 3
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/hugo_blog/about/"
    weight = 4

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'monokailight'
    tabWidth = 4
