baseURL = 'https://chajs226.github.io/'
theme = 'maverick'

# 시간대 설정 (한국 표준시)
timeZone = 'Asia/Seoul'

# 다국어 기본 설정
defaultContentLanguage = 'ko'
defaultContentLanguageInSubdir = true

[permalinks]
  pages = "/:slug"

# 언어별 설정
[languages]
  [languages.ko]
    languageCode = 'ko-kr'
    languageName = '한국어'
    title = "Junseong's Story"
    weight = 1
    timeZone = 'Asia/Seoul'
    
    [languages.ko.params]
      logo = '/assets/favicon.ico'
      description = "Junseong's Playground"
      author = 'Junseong'
      items = 10
      mainSections = ["posts", "notes"]
      
      [languages.ko.params.comments]
        enabled = false
      
      # 한국어용 소셜 미디어 링크
      [languages.ko.params.social]
        github = "https://github.com/chajs226"
        email = "mailto:chajs226@gmail.com"
    
    # 한국어 메뉴 (기본)
    [[menus.main]]
      identifier = "posts"
      name = "포스트"
      pageRef = "/posts"
      weight = 1
    [[menus.main]]
      identifier = "notes"
      name = "노트"
      pageRef = "/notes"
      weight = 2
    [[menus.main]]
      identifier = "about"
      name = "소개"
      pageRef = "/about"
      weight = 3

  [languages.en]
    languageCode = 'en-us'
    languageName = 'English'
    title = "Junseong's Story"
    weight = 2
    contentDir = "content/en"
    
    [languages.en.params]
      logo = '/assets/favicon.ico'
      description = "Junseong's Playground"
      author = 'Junseong Cha'
      items = 10
      mainSections = ["posts", "notes"]
      
      [languages.en.params.comments]
        enabled = false
      
      # 영어용 소셜 미디어 링크
      [languages.en.params.social]
        github = "https://github.com/chajs226"
        email = "mailto:chajs226@gmail.com"


[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'monokailight'
    tabWidth = 4
