baseURL = 'https://chajs226.github.io/'
languageCode = 'ko-kr'
title = "Junseong's Story"
theme = 'maverick'

[permalinks]
  pages = "/:slug"

[params]
  logo = '/assets/favicon.ico'
  description = "Junseong's Playgound"
  author = '차준성'
  items = 10
  # 모든 섹션의 콘텐츠를 메인에서 표시
  mainSections = ["posts", "notes"]
  
  [params.comments]
    enabled = false


[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    identifier = "notes"
    name = "Notes"
    url = "/notes/"
    weight = 3
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
    weight = 4

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'monokailight'
    tabWidth = 4
