baseURL = 'https://chajs226.github.io/'
theme = 'maverick'

# 다국어 기본 설정
defaultContentLanguage = 'ko'
defaultContentLanguageInSubdir = false

[permalinks]
  pages = "/:slug"

# 언어별 설정
[languages]
  [languages.ko]
    languageCode = 'ko-kr'
    languageName = '한국어'
    title = "Junseong's Story"
    weight = 1
    
    [languages.ko.params]
      logo = '/assets/favicon.ico'
      description = "Junseong's Playground"
      author = '차준성'
      items = 10
      mainSections = ["posts", "notes"]
      
      [languages.ko.params.comments]
        enabled = false
    
    # 한국어 메뉴
    [[languages.ko.menu.main]]
      identifier = "posts"
      name = "포스트"
      url = "/posts/"
      weight = 1
    [[languages.ko.menu.main]]
      identifier = "notes"
      name = "노트"
      url = "/notes/"
      weight = 2
    [[languages.ko.menu.main]]
      identifier = "about"
      name = "소개"
      url = "/about/"
      weight = 3

  [languages.en]
    languageCode = 'en-us'
    languageName = 'English'
    title = "Junseong's Story"
    weight = 2
    
    [languages.en.params]
      logo = '/assets/favicon.ico'
      description = "Junseong's Playground"
      author = 'Junseong Cha'
      items = 10
      mainSections = ["posts", "notes"]
      
      [languages.en.params.comments]
        enabled = false
    
    # 영어 메뉴
    [[languages.en.menu.main]]
      identifier = "posts"
      name = "Posts"
      url = "/en/posts/"
      weight = 1
    [[languages.en.menu.main]]
      identifier = "notes"
      name = "Notes"
      url = "/en/notes/"
      weight = 2
    [[languages.en.menu.main]]
      identifier = "about"
      name = "About"
      url = "/en/about/"
      weight = 3

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'monokailight'
    tabWidth = 4
